// <auto-generated />
using System;
using GearGenie.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GearGenie.Migrations
{
    [DbContext(typeof(GearContext))]
    [Migration("20241106185108_GearInit")]
    partial class GearInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GearGenie.Models.InventoryModels.Campaign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Admins")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("GearGenie.Models.InventoryModels.CampaignShop", b =>
                {
                    b.Property<int>("CampaignId")
                        .HasColumnType("int");

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.HasKey("CampaignId", "ShopId");

                    b.HasIndex("ShopId");

                    b.ToTable("CampaignShops");
                });

            modelBuilder.Entity("GearGenie.Models.InventoryModels.PlayerCharacter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CampaignId")
                        .HasColumnType("int");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PlayerCharacters");
                });

            modelBuilder.Entity("GearGenie.Models.InventoryModels.PlayerItem", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerCharacterId")
                        .HasColumnType("int");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.HasKey("ItemId", "PlayerCharacterId");

                    b.HasIndex("PlayerCharacterId");

                    b.ToTable("PlayerItems");
                });

            modelBuilder.Entity("GearGenie.Models.InventoryModels.Shop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Shops");
                });

            modelBuilder.Entity("GearGenie.Models.InventoryModels.ShopItem", b =>
                {
                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("ShopSection")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ShopId", "ItemId");

                    b.ToTable("ShopItems");
                });

            modelBuilder.Entity("GearGenie.Models.InventoryModels.CampaignShop", b =>
                {
                    b.HasOne("GearGenie.Models.InventoryModels.Campaign", "Campaign")
                        .WithMany("Shops")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GearGenie.Models.InventoryModels.Shop", "Shop")
                        .WithMany()
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("GearGenie.Models.InventoryModels.PlayerItem", b =>
                {
                    b.HasOne("GearGenie.Models.InventoryModels.PlayerCharacter", "PlayerCharacter")
                        .WithMany("Items")
                        .HasForeignKey("PlayerCharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerCharacter");
                });

            modelBuilder.Entity("GearGenie.Models.InventoryModels.ShopItem", b =>
                {
                    b.HasOne("GearGenie.Models.InventoryModels.Shop", "Shop")
                        .WithMany("Items")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("GearGenie.Models.InventoryModels.Campaign", b =>
                {
                    b.Navigation("Shops");
                });

            modelBuilder.Entity("GearGenie.Models.InventoryModels.PlayerCharacter", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("GearGenie.Models.InventoryModels.Shop", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
